name: Run SSH command

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run SSH command
        uses: appleboy/ssh-action@v1.0.0
        timeout-minutes: 60
        with:
          command_timeout: "60m"
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.pull_request.merged }}" == true && ("${{ github.event.pull_request.base.ref }}" == "staging") ]]; then
              cd /root/apk-reproduce/Deku-SMS-Android/ci && \
              ./ci_cd.sh ${{ secrets.JKS_PASS }}
            else
              echo "PR is not merged into '${{ github.event.pull_request.base.ref }}'. Workflow will not run."
              exit 1
            fi
